#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_MENU1                               100
#define IDI_SOCKET                              103
#define IDI_SOCKETSM                            105
#define IDB_ADD                                 109
#define IDB_EXIT                                111
#define IDB_REMOVE                              113
#define IDD_HELP_ABOUT                          115
#define IDD_ADDHOST                             117
#define IDI_PROFILESM                           119
#define IDI_PROFILE                             121
#define IDI_ADDSM                               123
#define IDI_REMOVESM                            125
#define IDI_SAVESM                              127
#define IDI_SAVEASSM                            129
#define IDI_OPENSM                              131
#define IDI_NEWSM                               133
#define IDI_EDITSM                              135
#define IDB_HOSTADD                             137
#define IDB_HOSTREMOVE                          139
#define IDB_HOSTEDIT                            141
#define IDB_NEW                                 143
#define IDB_OPEN                                145
#define IDB_SAVE                                147
#define IDB_SAVEAS                              149
#define IDB_HELP                                151
#define IDB_SETTINGS                            153
#define IDB_PROFILE                             155
#define IDB_SYSTRAY                             157
#define IDB_HOSTKNOCK                           160
#define IDB_PROFILESM                           162
#define IDD_KNOCKING                            164
#define IDD_SETTINGS                            166
#define ID_CB_SYSTRAY                           40000
#define ID_HOST_ADD                             40000
#define ID_KNOCK_PROGRESS                       40000
#define ID_LV_PORTS                             40000
#define ID_ABOUT_LABEL                          40001
#define ID_CB_STEXITONLY                        40001
#define ID_FILE_EXIT                            40001
#define ID_CB_VKNOCK                            40002
#define ID_HOST_REMOVE                          40002
#define ID_TXT_ALIAS                            40002
#define ID_CB_AUTOCLOSE                         40003
#define ID_EDIT_SETTINGS                        40003
#define ID_TXT_HOST                             40003
#define ID_HELP_ABOUT                           40004
#define ID_TXT_PORT                             40004
#define ID_FILE_OPEN                            40005
#define ID_TXT_DELAY                            40005
#define ID_BTN_REMOVE                           40006
#define ID_FILE_SAVE                            40006
#define ID_BTN_ADD                              40007
#define ID_FILE_SAVEAS                          40007
#define ID_HOST_EDIT                            40008
#define ID_RAD_TCP                              40008
#define ID_FILE_NEW                             40009
#define ID_RAD_UDP                              40009
#define ID_HOST_KNOCK                           40010
#define ID_RE_EXPERT                            40011
#define ID_TXT_PASSWD                           40012
#define ID_TXT_VPASSWD                          40013
#define ID_CB_REQPASSWD                         40014
